# scripts/13_metrics_snapshot.R
# ============================================================================
# Refresh the auto-generated "Current snapshot" block in docs/metrics.md.
# ============================================================================
# Reads the headline output tables written by script 10 (gap_overview) and
# rewrites ONLY the text between the METRICS_SNAPSHOT markers in docs/metrics.md,
# so the metrics reference always carries the current run's figures without hand
# edits. Idempotent, and fail-safe: on any problem it warns and leaves
# metrics.md untouched (never stops the build).
#
# Run via run_metrics() or the `metrics_snapshot` target in tar_make().

# Best-effort setup (for p_output / COUNTRY_CODE / get_snapshot_date); the core
# works off the CSVs alone if setup is unavailable.
tryCatch(
  source(here::here("scripts", "00_setup.R")),
  error = function(e) message("13_metrics_snapshot: 00_setup not sourced (", conditionMessage(e), ")")
)

# ---- formatting helpers ----------------------------------------------------
.msnap_num <- function(x) {
  x <- suppressWarnings(as.numeric(x))
  if (length(x) != 1 || is.na(x)) return("n/a")
  format(x, big.mark = ",", trim = TRUE, scientific = FALSE)
}
.msnap_raw <- function(x) if (length(x) != 1 || is.na(x) || !nzchar(x)) "n/a" else as.character(x)
.msnap_pct <- function(x) if (length(x) != 1 || is.na(x)) "n/a" else paste0(as.character(x), "%")

.msnap_read <- function(dir, file) {
  p <- file.path(dir, file)
  if (!file.exists(p)) return(NULL)
  tryCatch(
    utils::read.csv(p, colClasses = "character", check.names = FALSE, stringsAsFactors = FALSE),
    error = function(e) NULL
  )
}

.msnap_table <- function(df) {
  if (is.null(df) || !nrow(df)) return("_(table unavailable — rerun the pipeline)_")
  nm  <- names(df)
  hdr <- paste0("| ", paste(nm, collapse = " | "), " |")
  sep <- paste0("|", paste(rep(" --- ", length(nm)), collapse = "|"), "|")
  rows <- apply(df, 1L, function(r) paste0("| ", paste(trimws(as.character(r)), collapse = " | "), " |"))
  paste(c(hdr, sep, rows), collapse = "\n")
}

# ---- build the markdown block (pure: dir + dates in, string out) -----------
build_metrics_block <- function(tables_dir, snap_date = "n/a", gen_date = "n/a") {
  dash      <- .msnap_read(tables_dir, "dashboard_summary_long.csv")
  by_rank   <- .msnap_read(tables_dir, "overview_taxonomic_by_rank.csv")
  by_threat <- .msnap_read(tables_dir, "overview_taxonomic_by_threat.csv")
  priority  <- .msnap_read(tables_dir, "priority_summary.csv")
  if (is.null(dash)) return(NULL)

  # Label the unranked/blank IUCN status so the table cell is not empty.
  if (!is.null(by_threat) && "threatStatus" %in% names(by_threat)) {
    blank <- is.na(by_threat$threatStatus) | trimws(by_threat$threatStatus) == ""
    by_threat$threatStatus[blank] <- "(no status)"
  }

  v  <- stats::setNames(as.character(dash$value), dash$metric)
  gN <- function(k) .msnap_num(v[[k]])
  gR <- function(k) .msnap_raw(v[[k]])
  gP <- function(k) .msnap_pct(v[[k]])

  lines <- c(
    "<!-- METRICS_SNAPSHOT:BEGIN (auto-generated by scripts/13_metrics_snapshot.R — do not edit inside this block) -->",
    sprintf("## Current snapshot — as of %s", gR("analysis_date")),
    "",
    sprintf("> Auto-generated from the pipeline output tables on %s; refreshed by `run_metrics()` /", gen_date),
    "> the `metrics_snapshot` target on every `tar_make()`. **Do not hand-edit inside the markers.**",
    sprintf("> GBIF cube snapshot: **%s** &middot; total occurrences: **%s** &middot; basis types: **%s**.",
            snap_date, gN("total_occurrences"), gR("n_basis_types")),
    "",
    "**Spatial coverage**",
    "",
    "| Grid | Cells | With data | Zero-coverage | Coverage |",
    "|---|--:|--:|--:|--:|",
    sprintf("| 10 km | %s | %s | %s | %s |",
            gN("cells_10km_total"), gN("cells_10km_with_data"), gN("cells_10km_zero"), gP("cells_10km_pct_coverage")),
    sprintf("| 50 km | %s | %s | %s | %s |",
            gN("cells_50km_total"), gN("cells_50km_with_data"), gN("cells_50km_zero"), gP("cells_50km_pct_coverage")),
    "",
    sprintf("**Temporal** &mdash; years %s&ndash;%s (%s yr) &middot; median staleness (10 km) %s mo &middot; cells unsampled &gt;1 yr %s, &gt;5 yr %s.",
            gR("year_min"), gR("year_max"), gR("year_span"), gR("median_staleness_months_10km"),
            gP("pct_stale_1y_10km"), gP("pct_stale_5y_10km")),
    "",
    sprintf("**Taxonomic** &mdash; reference %s &middot; in GBIF %s (%s) &middot; missing %s. Threatened (CR/EN/VU/NT): reference %s &middot; in GBIF %s &middot; missing %s.",
            gN("taxa_in_reference"), gN("taxa_in_gbif"), gP("taxa_pct_coverage"), gN("taxa_missing"),
            gN("threatened_in_reference"), gN("threatened_in_gbif"), gN("threatened_missing")),
    "",
    "Coverage by rank:",
    "",
    .msnap_table(by_rank),
    "",
    "Coverage by threat status:",
    "",
    .msnap_table(by_threat),
    "",
    "Priority counts:",
    "",
    .msnap_table(priority),
    "<!-- METRICS_SNAPSHOT:END -->"
  )
  paste(lines, collapse = "\n")
}

# ---- splice the block into docs/metrics.md ---------------------------------
metrics_snapshot <- function() {
  cc <- tryCatch(COUNTRY_CODE, error = function(e) Sys.getenv("GBIF_GAP_COUNTRY", "SE"))
  tables_dir <- tryCatch(here::here(p_output, "tables"),
                         error = function(e) here::here("data", cc, "output", "tables"))
  snap_date <- tryCatch(as.character(get_snapshot_date()), error = function(e) NA_character_)
  gen_date  <- format(Sys.Date())

  block <- build_metrics_block(tables_dir, snap_date = .msnap_raw(snap_date), gen_date = gen_date)
  if (is.null(block)) {
    message("13_metrics_snapshot: dashboard_summary_long.csv not found in ", tables_dir,
            " — run script 10 (gap_overview) first. metrics.md unchanged.")
    return(invisible(FALSE))
  }

  md_path <- here::here("docs", "metrics.md")
  if (!file.exists(md_path)) {
    message("13_metrics_snapshot: ", md_path, " not found; nothing to update.")
    return(invisible(FALSE))
  }
  txt <- paste(readLines(md_path, warn = FALSE), collapse = "\n")

  i <- regexpr("<!-- METRICS_SNAPSHOT:BEGIN", txt, fixed = TRUE)
  j <- regexpr("METRICS_SNAPSHOT:END -->",   txt, fixed = TRUE)
  if (i < 1L || j < 1L) {
    message("13_metrics_snapshot: markers not found in metrics.md; leaving file unchanged. ",
            "Restore the <!-- METRICS_SNAPSHOT:BEGIN ... END --> block to re-enable.")
    return(invisible(FALSE))
  }
  pre  <- substr(txt, 1L, i - 1L)
  post <- substr(txt, j + attr(j, "match.length"), nchar(txt))
  writeLines(paste0(pre, block, post), md_path)
  message("13_metrics_snapshot: refreshed the snapshot block in docs/metrics.md (as of ",
          format(Sys.Date()), ").")
  invisible(TRUE)
}

# Auto-run when sourced by the target / run_metrics(); guardable for testing.
if (!isTRUE(getOption("msnap.no_run"))) metrics_snapshot()
